name: Build

on: [push]

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npx vsce@2.11.0 package --allow-star-activation

      - name: Check Git Status
        run: git status --porcelain
